name: build and deploy to github pages
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.1"
          cache: "pip"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: auth as github-actions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: push to gh-pages branch
        run: mkdocs gh-deploy --message Automated Build and Deploy --force