name: build and deploy to github pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.1"
          cache: "pip"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: build
        run: mkdocs build
      - name: capture build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: site
      - name: push to gh-pages branch
        run: mkdocs gh-deploy